# This is a basic workflow to help you get started with Actions

name: Deploy MkDocs to Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        
      - name: Build MkDocs
        uses: Tiryoh/actions-mkdocs@v0.15.0
        with:
          # pip version of MkDocs
          mkdocs_version: 1.3.0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3.3.0
        
      - name: Build React Homepage
        run: |
          cd wiki-homepage
          npm install
          npm run build
          
      - name: Prepare files for deployment
        run: |
          mkdir pages-upload
          ls
          cp -r site pages-upload/docs/
          cp -r wiki-homepage/build/* pages-upload/
          
          
      - name: Deploy to Github Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          build_dir: pages-upload
          fqdn: wiki.xjtlu.zone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    
